archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-test
    dir: provider
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ignore: []
    ldflags:
      - -X github.com/dougsong/pulumi-ci-test/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-xyz/
    sort: asc
    use: git
release:
  disable: false
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"