// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Ecs.Outputs
{

    [OutputType]
    public sealed class InstanceDataVolume
    {
        public readonly bool? DeleteWithInstance;
        public readonly int Size;
        public readonly string VolumeType;

        [OutputConstructor]
        private InstanceDataVolume(
            bool? deleteWithInstance,

            int size,

            string volumeType)
        {
            DeleteWithInstance = deleteWithInstance;
            Size = size;
            VolumeType = volumeType;
        }
    }
}
