// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace ecs {
    export interface InstanceDataVolume {
        deleteWithInstance?: boolean;
        size: number;
        volumeType: string;
    }

    export interface InstanceGpuDevice {
        count: number;
        encryptedMemorySize: number;
        memorySize: number;
        productName: string;
    }

    export interface InstanceSecondaryNetworkInterface {
        primaryIpAddress: string;
        securityGroupIds: string[];
        subnetId: string;
    }

    export interface InstanceTag {
        key: string;
        value: string;
    }

}
