// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ZhenRan.PulumiPackage.Volcengine.Ecs.Inputs
{

    public sealed class InstanceSecondaryNetworkInterfaceGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("primaryIpAddress")]
        public Input<string>? PrimaryIpAddress { get; set; }

        [Input("securityGroupIds", required: true)]
        private InputList<string>? _securityGroupIds;
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("subnetId", required: true)]
        public Input<string> SubnetId { get; set; } = null!;

        public InstanceSecondaryNetworkInterfaceGetArgs()
        {
        }
        public static new InstanceSecondaryNetworkInterfaceGetArgs Empty => new InstanceSecondaryNetworkInterfaceGetArgs();
    }
}
